createTable = CREATE TABLE IF NOT EXISTS USERS (id SERIAL PRIMARY KEY, name VARCHAR(40), lastName VARCHAR(30), age INT)
dropTable = Drop TABLE IF EXISTS USERS
saveUser = INSERT INTO USERS(name, lastName, age) VALUES (?, ?, ?)
removeUserById = DELETE FROM USERS WHERE id = ?
allUsers = SELECT * FROM USERS
cleanTable = TRUNCATE TABLE USERS